### ISSUE TITLE
code release

### ISSUE THREAD

**Issue by CHMimilanlan** [J-X-Chen/GGAvatar#1]
I'm really interested in your works, I'm wondering when the code will be released?

**Comment by RR-28023** [comment]
+1!

**Comment by J-X-Chen** [comment]
Sorry everyone, due to being busy applying for postgraduate recently, the code has not been organized and commented out. If you need a version that is currently difficult to understand but can be run, please contact me by email.

**Comment by hengyu-wang** [comment]
> Sorry everyone, due to being busy applying for postgraduate recently, the code has not been organized and commented out. If you need a version that is currently difficult to understand but can be run, please contact me by email.

I am very interested in your work. If you could send me a copy of the code, I would be very grateful. My email is why3065619030@163.com.

**Comment by gitPZH** [comment]
> 对不起大家，由于最近忙于申请研究生，代码一直没有整理和注释掉。如果您需要当前难以理解但可以运行的版本，请通过电子邮件与我联系。

我对你的工作很感兴趣。如果您能将代码副本也发送给我一份，我将不胜感激。我的电子邮件是。[1175512547@qq.com](mailto:1175512547@qq.com)

**Comment by XingFen-Xie** [comment]
> Sorry everyone, due to being busy applying for postgraduate recently, the code has not been organized and commented out. If you need a version that is currently difficult to understand but can be run, please contact me by email.

Hi, I’m very interested in your work and would be truly grateful if you could share the code with me. If possible, please send it to my email: 2983150767@qq.com. Many thanks in advance!
